{% set name = "cdsodatacli" %}
{% set version = "2024.12.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cdsodatacli-{{ version }}.tar.gz
  sha256: 13268b9f7122d2029fd24dc6ba8e92462563ddf751d63a88df0e3ea4450c7309

build:
  entry_points:
    - queryCDS = cdsodatacli.query:query_client
    - downloadFromCDS = cdsodatacli.download:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - geopandas
    - numpy
    - requests
    - shapely
    - tqdm
    - pyyaml

test:
  imports:
    - cdsodatacli
  commands:
    - pip check
    - queryCDS --help
    - downloadFromCDS --help
  requires:
    - pip

about:
  home: https://github.com/umr-lops/cdsodatacli
  summary: OData client for Copernicus Data Space catalog
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agrouaze
