{% set name = "cdsodatacli" %}
{% set version = "2025.10.22.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cdsodatacli-{{ version }}.tar.gz
  sha256: 97a92795a7af7ba6e3ad795cdda96199f770f8107cf3c5ebd6c72ff23940348a

build:
  entry_points:
    - queryCDS = cdsodatacli.query:query_client
    - downloadFromCDS = cdsodatacli.download:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - geopandas
    - numpy
    - requests
    - shapely
    - tqdm
    - pyyaml
    - geodatasets
    - cartopy
    - python-dotenv

test:
  imports:
    - cdsodatacli
  commands:
    - pip check
    - queryCDS --help
    - downloadFromCDS --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/umr-lops/cdsodatacli
  summary: OData client for Copernicus Data Space catalog
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agrouaze
