{% set name = "cdsodatacli" %}
{% set version = "2024.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cdsodatacli-{{ version }}.tar.gz
  sha256: bb9c7b57c552fb26be5413a06db2b316b2a176d3f69f470a03e21f6b2f3417c6

build:
  entry_points:
    - queryCDS = cdsodatacli.query:query_client
    - downloadFromCDS = cdsodatacli.download:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - geopandas
    - numpy
    - requests
    - shapely
    - tqdm
    - pyyaml
    - geodatasets
    - cartopy
    - python-dotenv

test:
  imports:
    - cdsodatacli
  commands:
    - pip check
    - queryCDS --help
    - downloadFromCDS --help
  requires:
    - pip

about:
  home: https://github.com/umr-lops/cdsodatacli
  summary: OData client for Copernicus Data Space catalog
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - agrouaze
